/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    classes: Class;
    teachers: Teacher;
    'schedule-slots': ScheduleSlot;
    'pricing-plans': PricingPlan;
    faqs: Faq;
    reviews: Review;
    posts: Post;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    teachers: TeachersSelect<false> | TeachersSelect<true>;
    'schedule-slots': ScheduleSlotsSelect<false> | ScheduleSlotsSelect<true>;
    'pricing-plans': PricingPlansSelect<false> | PricingPlansSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('es' | 'en') | ('es' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: 'es' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Desactiva «Visible» para ocultar una clase en la web sin borrarla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: number;
  slug: string;
  title: string;
  description: string;
  durationMin: number;
  level: 'all' | 'beginner' | 'intermediate';
  image?: (number | null) | Media;
  /**
   * URL externa de imagen (se usa si no hay imagen subida)
   */
  imageUrl?: string | null;
  /**
   * Si está desactivado, la clase no aparece en /clases ni en la landing.
   */
  visible?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers".
 */
export interface Teacher {
  id: number;
  slug: string;
  name: string;
  role: string;
  bio: string;
  photo?: (number | null) | Media;
  /**
   * URL externa de imagen (se usa si no hay foto subida)
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Franjas del calendario. Desactiva «Visible» para ocultar una hora sin borrarla.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-slots".
 */
export interface ScheduleSlot {
  id: number;
  day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
  /**
   * Formato 24h, p. ej. 09:30
   */
  time: string;
  class: number | Class;
  teacher?: (number | null) | Teacher;
  /**
   * Si está desactivado, este horario no aparece en /horarios ni en la landing.
   */
  visible?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Máximo 4 planes. Desactiva «Visible» para ocultar un plan sin borrarlo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans".
 */
export interface PricingPlan {
  id: number;
  /**
   * Identificador interno, p. ej. bono-8
   */
  slug: string;
  name: string;
  price: number;
  currency: string;
  period: 'single' | 'monthly';
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  /**
   * Si está desactivado, el plan no aparece en /precios ni en la landing.
   */
  visible?: boolean | null;
  /**
   * Menor número = aparece antes.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Preguntas frecuentes de la página de precios. Desactiva «Visible» para ocultarlas en la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  /**
   * Si está desactivado, la pregunta no aparece en /precios.
   */
  visible?: boolean | null;
  /**
   * Menor número = aparece antes.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * P. ej. «Alumna de Vinyasa»
   */
  context?: string | null;
  text: string;
  rating: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * Artículos del blog. Desactiva «Visible» para ocultarlos en la web.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * URL del artículo, p. ej. beneficios-del-yin-yoga
   */
  slug: string;
  /**
   * Resumen corto para la tarjeta del listado
   */
  excerpt: string;
  coverImage?: (number | null) | Media;
  /**
   * URL externa (solo si no hay imagen subida)
   */
  coverImageUrl?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Si está desactivado, el artículo no aparece en el blog público.
   */
  visible?: boolean | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'classes';
        value: number | Class;
      } | null)
    | ({
        relationTo: 'teachers';
        value: number | Teacher;
      } | null)
    | ({
        relationTo: 'schedule-slots';
        value: number | ScheduleSlot;
      } | null)
    | ({
        relationTo: 'pricing-plans';
        value: number | PricingPlan;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  description?: T;
  durationMin?: T;
  level?: T;
  image?: T;
  imageUrl?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "teachers_select".
 */
export interface TeachersSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "schedule-slots_select".
 */
export interface ScheduleSlotsSelect<T extends boolean = true> {
  day?: T;
  time?: T;
  class?: T;
  teacher?: T;
  visible?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-plans_select".
 */
export interface PricingPlansSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  price?: T;
  currency?: T;
  period?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  featured?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  visible?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  context?: T;
  text?: T;
  rating?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  coverImage?: T;
  coverImageUrl?: T;
  content?: T;
  visible?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Marca, logo, colores, contacto, imágenes principales y qué páginas/secciones se muestran.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Usado en textos con {brandName}.
   */
  brandName: string;
  /**
   * Nombre usado en toda la web: metas, WhatsApp, tagline, «Hola, soy…», etc. Usa {teacherName} en los textos.
   */
  teacherName: string;
  /**
   * Normalmente en mayúsculas, como aparece junto al símbolo.
   */
  logoText: string;
  /**
   * Puedes usar {teacherName} y {brandName}.
   */
  tagline?: string | null;
  /**
   * Si subes una imagen, sustituye el símbolo SVG por defecto.
   */
  logo?: (number | null) | Media;
  /**
   * Solo si no hay imagen subida.
   */
  logoUrl?: string | null;
  showLogoMark?: boolean | null;
  showLogoText?: boolean | null;
  showTagline?: boolean | null;
  colors: {
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    deep: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    deepDark: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    teal: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    tealDark: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    aqua: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    sky: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    sand: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    linen: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    wood: string;
    /**
     * Color HEX, p. ej. #0F4C5C. El cuadrado muestra la vista previa y permite elegir el color.
     */
    ink: string;
  };
  contact: {
    /**
     * Solo dígitos con prefijo país, sin + ni espacios. Ej. 34610429326. Usado en TODOS los WhatsApp de la web.
     */
    whatsappPhone: string;
    /**
     * Texto visible junto al icono de teléfono en Contacto.
     */
    whatsappDisplay: string;
    /**
     * Correo mostrado en Contacto y en el footer.
     */
    email: string;
    address?: string | null;
    instagram?: string | null;
    facebook?: string | null;
    spotify?: string | null;
  };
  images?: {
    hero?: (number | null) | Media;
    heroUrl?: string | null;
    studio?: (number | null) | Media;
    studioUrl?: string | null;
    contact?: (number | null) | Media;
    contactUrl?: string | null;
  };
  /**
   * Fotos de la página /estudio. La primera marcada como «Destacada» ocupa más espacio.
   */
  studioGallery?:
    | {
        image?: (number | null) | Media;
        imageUrl?: string | null;
        alt?: string | null;
        featured?: boolean | null;
        id?: string | null;
      }[]
    | null;
  pages?: {
    classes?: boolean | null;
    schedule?: boolean | null;
    studio?: boolean | null;
    about?: boolean | null;
    blog?: boolean | null;
    pricing?: boolean | null;
    contact?: boolean | null;
  };
  headerNav?: {
    home?: boolean | null;
    classes?: boolean | null;
    schedule?: boolean | null;
    /**
     * Oculto en el header por defecto. La página sigue accesible si está activa en «Páginas visibles».
     */
    studio?: boolean | null;
    about?: boolean | null;
    blog?: boolean | null;
    pricing?: boolean | null;
    contact?: boolean | null;
    cta?: boolean | null;
  };
  footerNav?: {
    classes?: boolean | null;
    schedule?: boolean | null;
    studio?: boolean | null;
    about?: boolean | null;
    blog?: boolean | null;
    pricing?: boolean | null;
    contact?: boolean | null;
  };
  footerSocial?: {
    facebook?: boolean | null;
    instagram?: boolean | null;
    email?: boolean | null;
    whatsapp?: boolean | null;
    spotify?: boolean | null;
  };
  /**
   * Arrastra para cambiar el orden. Desactiva «Visible» para ocultar una sección.
   */
  landingSections?:
    | {
        section:
          | 'hero'
          | 'features'
          | 'studio'
          | 'quote'
          | 'classes'
          | 'schedule'
          | 'about'
          | 'pricing'
          | 'reviews'
          | 'contact';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Arrastra para poner uno encima del otro. Desactiva «Visible» para ocultar un botón.
   */
  landingStudioCtas?:
    | {
        section: 'explore' | 'rental';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Arrastra para cambiar el orden. Desactiva «Visible» para ocultar una sección.
   */
  aboutSections?:
    | {
        section: 'intro' | 'story' | 'philosophy' | 'training' | 'stats' | 'reviews' | 'values' | 'offMat' | 'cta';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Arrastra para cambiar el orden. Desactiva «Visible» para ocultar una sección.
   */
  studioSections?:
    | {
        section: 'hero' | 'intro' | 'gallery' | 'rental';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Arrastra para cambiar el orden. Desactiva «Visible» para ocultar una sección.
   */
  pricingSections?:
    | {
        section: 'hero' | 'plans' | 'faq';
        visible?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Títulos, subtítulos y textos de la web. Cambia el idioma arriba a la derecha del admin para editar ES/EN.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  meta: {
    title: string;
    description: string;
  };
  nav?: {
    home?: string | null;
    classes?: string | null;
    schedule?: string | null;
    studio?: string | null;
    about?: string | null;
    blog?: string | null;
    pricing?: string | null;
    contact?: string | null;
    cta?: string | null;
  };
  hero: {
    eyebrow?: string | null;
    title: string;
    subtitle?: string | null;
    cta?: string | null;
    imageAlt?: string | null;
  };
  features?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  studio?: {
    label?: string | null;
    title?: string | null;
    text?: string | null;
    cta?: string | null;
    ctaRental?: string | null;
    imageAlt?: string | null;
    galleryLabel?: string | null;
    galleryTitle?: string | null;
    gallerySubtitle?: string | null;
    rental?: {
      label?: string | null;
      title?: string | null;
      text?: string | null;
      cta?: string | null;
      whatsappMessage?: string | null;
      highlights?: {
        light?: string | null;
        equip?: string | null;
        groups?: string | null;
      };
    };
  };
  quote?: {
    text?: string | null;
    author?: string | null;
  };
  classes?: {
    label?: string | null;
    title?: string | null;
    subtitle?: string | null;
    cta?: string | null;
  };
  schedule?: {
    label?: string | null;
    title?: string | null;
    subtitle?: string | null;
    book?: string | null;
  };
  pricing?: {
    label?: string | null;
    title?: string | null;
    subtitle?: string | null;
    cta?: string | null;
    popular?: string | null;
    faq?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
    };
  };
  reviews?: {
    label?: string | null;
    title?: string | null;
  };
  contact?: {
    label?: string | null;
    title?: string | null;
    subtitle?: string | null;
    imageAlt?: string | null;
  };
  about?: {
    label?: string | null;
    /**
     * Ej. Hola, soy {name}
     */
    title?: string | null;
    cta?: string | null;
    imageAlt?: string | null;
  };
  footer?: {
    tagline?: string | null;
    explore?: string | null;
    follow?: string | null;
    /**
     * Ej. © {year} Blau Yoga. Todos los derechos reservados.
     */
    rights?: string | null;
    values?: string | null;
  };
  blog?: {
    label?: string | null;
    title?: string | null;
    subtitle?: string | null;
    metaTitle?: string | null;
    metaDescription?: string | null;
    readMore?: string | null;
    back?: string | null;
    empty?: string | null;
  };
  aboutPage?: {
    story?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      steps?: {
        discover?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        train?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        change?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        teach?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
      };
    };
    philosophy?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      points?: {
        accessible?: {
          title?: string | null;
          text?: string | null;
        };
        breath?: {
          title?: string | null;
          text?: string | null;
        };
        levels?: {
          title?: string | null;
          text?: string | null;
        };
        safe?: {
          title?: string | null;
          text?: string | null;
        };
      };
    };
    training?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      items?: {
        main?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        extra?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        retreats?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
      };
    };
    values?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      items?: {
        authenticity?: {
          title?: string | null;
          text?: string | null;
        };
        listening?: {
          title?: string | null;
          text?: string | null;
        };
        community?: {
          title?: string | null;
          text?: string | null;
        };
        awareness?: {
          title?: string | null;
          text?: string | null;
        };
        accessibility?: {
          title?: string | null;
          text?: string | null;
        };
      };
    };
    offMat?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      items?: {
        barcelona?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        rituals?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
        inspire?: {
          label?: string | null;
          title?: string | null;
          text?: string | null;
        };
      };
    };
    cta?: {
      label?: string | null;
      title?: string | null;
      subtitle?: string | null;
      primary?: string | null;
      whatsapp?: string | null;
      instagram?: string | null;
      /**
       * Puedes usar {teacherName}.
       */
      whatsappMessage?: string | null;
    };
  };
  /**
   * Ej. { "classes": { "metaTitle": "...", "metaDescription": "..." }, ... }
   */
  pageMeta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  teacherName?: T;
  logoText?: T;
  tagline?: T;
  logo?: T;
  logoUrl?: T;
  showLogoMark?: T;
  showLogoText?: T;
  showTagline?: T;
  colors?:
    | T
    | {
        deep?: T;
        deepDark?: T;
        teal?: T;
        tealDark?: T;
        aqua?: T;
        sky?: T;
        sand?: T;
        linen?: T;
        wood?: T;
        ink?: T;
      };
  contact?:
    | T
    | {
        whatsappPhone?: T;
        whatsappDisplay?: T;
        email?: T;
        address?: T;
        instagram?: T;
        facebook?: T;
        spotify?: T;
      };
  images?:
    | T
    | {
        hero?: T;
        heroUrl?: T;
        studio?: T;
        studioUrl?: T;
        contact?: T;
        contactUrl?: T;
      };
  studioGallery?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        alt?: T;
        featured?: T;
        id?: T;
      };
  pages?:
    | T
    | {
        classes?: T;
        schedule?: T;
        studio?: T;
        about?: T;
        blog?: T;
        pricing?: T;
        contact?: T;
      };
  headerNav?:
    | T
    | {
        home?: T;
        classes?: T;
        schedule?: T;
        studio?: T;
        about?: T;
        blog?: T;
        pricing?: T;
        contact?: T;
        cta?: T;
      };
  footerNav?:
    | T
    | {
        classes?: T;
        schedule?: T;
        studio?: T;
        about?: T;
        blog?: T;
        pricing?: T;
        contact?: T;
      };
  footerSocial?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        email?: T;
        whatsapp?: T;
        spotify?: T;
      };
  landingSections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  landingStudioCtas?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  aboutSections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  studioSections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  pricingSections?:
    | T
    | {
        section?: T;
        visible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  nav?:
    | T
    | {
        home?: T;
        classes?: T;
        schedule?: T;
        studio?: T;
        about?: T;
        blog?: T;
        pricing?: T;
        contact?: T;
        cta?: T;
      };
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        subtitle?: T;
        cta?: T;
        imageAlt?: T;
      };
  features?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  studio?:
    | T
    | {
        label?: T;
        title?: T;
        text?: T;
        cta?: T;
        ctaRental?: T;
        imageAlt?: T;
        galleryLabel?: T;
        galleryTitle?: T;
        gallerySubtitle?: T;
        rental?:
          | T
          | {
              label?: T;
              title?: T;
              text?: T;
              cta?: T;
              whatsappMessage?: T;
              highlights?:
                | T
                | {
                    light?: T;
                    equip?: T;
                    groups?: T;
                  };
            };
      };
  quote?:
    | T
    | {
        text?: T;
        author?: T;
      };
  classes?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        cta?: T;
      };
  schedule?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        book?: T;
      };
  pricing?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        cta?: T;
        popular?: T;
        faq?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
            };
      };
  reviews?:
    | T
    | {
        label?: T;
        title?: T;
      };
  contact?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        imageAlt?: T;
      };
  about?:
    | T
    | {
        label?: T;
        title?: T;
        cta?: T;
        imageAlt?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        explore?: T;
        follow?: T;
        rights?: T;
        values?: T;
      };
  blog?:
    | T
    | {
        label?: T;
        title?: T;
        subtitle?: T;
        metaTitle?: T;
        metaDescription?: T;
        readMore?: T;
        back?: T;
        empty?: T;
      };
  aboutPage?:
    | T
    | {
        story?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              steps?:
                | T
                | {
                    discover?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    train?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    change?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    teach?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                  };
            };
        philosophy?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              points?:
                | T
                | {
                    accessible?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    breath?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    levels?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    safe?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                  };
            };
        training?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    main?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    extra?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    retreats?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                  };
            };
        values?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    authenticity?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    listening?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    community?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    awareness?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                    accessibility?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                        };
                  };
            };
        offMat?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              items?:
                | T
                | {
                    barcelona?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    rituals?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                    inspire?:
                      | T
                      | {
                          label?: T;
                          title?: T;
                          text?: T;
                        };
                  };
            };
        cta?:
          | T
          | {
              label?: T;
              title?: T;
              subtitle?: T;
              primary?: T;
              whatsapp?: T;
              instagram?: T;
              whatsappMessage?: T;
            };
      };
  pageMeta?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}